name: sized_context_example
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  universal_platform:
    path: ../

flutter:
  uses-material-design: true
